export const ipcChannels = {
  activateTab: "pulse-md:activate-tab",
  addWordToSpellCheckerDictionary:
    "pulse-md:add-word-to-spell-checker-dictionary",
  acknowledgeDocumentSave: "pulse-md:acknowledge-document-save",
  acknowledgeExternalDocumentChange:
    "pulse-md:acknowledge-external-document-change",
  acknowledgeTabHydration: "pulse-md:acknowledge-tab-hydration",
  acknowledgeTabDetachSourceRetired:
    "pulse-md:acknowledge-tab-detach-source-retired",
  acknowledgeCliEditorFocus: "pulse-md:acknowledge-cli-editor-focus",
  acknowledgeCliTabsOpen: "pulse-md:acknowledge-cli-tabs-open",
  activateWindowsMenuItem: "pulse-md:activate-windows-menu-item",
  beginTabDrag: "pulse-md:begin-tab-drag",
  acquireSettingsSession: "pulse-md:acquire-settings-session",
  bootstrap: "pulse-md:bootstrap",
  closeReady: "pulse-md:close-ready",
  windowClosePrepared: "pulse-md:window-close-prepared",
  cliEditorFocusRequested: "pulse-md:cli-editor-focus-requested",
  cliTabsOpenRequested: "pulse-md:cli-tabs-open-requested",
  command: "pulse-md:command",
  commandHandled: "pulse-md:command-handled",
  commitSettingsImport: "pulse-md:commit-settings-import",
  commitTabTransfer: "pulse-md:commit-tab-transfer",
  confirmTabTransfer: "pulse-md:confirm-tab-transfer",
  copyEditorLink: "pulse-md:copy-editor-link",
  copyHeadingLink: "pulse-md:copy-heading-link",
  copyPath: "pulse-md:copy-path",
  discardSettingsImport: "pulse-md:discard-settings-import",
  endTabDrag: "pulse-md:end-tab-drag",
  editorReady: "pulse-md:editor-ready",
  editorContextMenu: "pulse-md:editor-context-menu",
  editFocusedControl: "pulse-md:edit-focused-control",
  exportSettings: "pulse-md:export-settings",
  exitLaunchBenchmark: "pulse-md:exit-launch-benchmark",
  externalDocumentChange: "pulse-md:external-document-change",
  finalizeCloseTab: "pulse-md:finalize-close-tab",
  deleteScratch: "pulse-md:delete-scratch",
  deleteWindowProfile: "pulse-md:delete-window-profile",
  getScratchPreview: "pulse-md:get-scratch-preview",
  getRecoveryWindowMaximized: "pulse-md:get-recovery-window-maximized",
  getScratches: "pulse-md:get-scratches",
  getWindowProfiles: "pulse-md:get-window-profiles",
  getCurrentWindowProfileSeed: "pulse-md:get-current-window-profile-seed",
  getWindowMaximized: "pulse-md:get-window-maximized",
  getWindowsMenuSnapshot: "pulse-md:get-windows-menu-snapshot",
  completeWindowProfilePicker: "pulse-md:complete-window-profile-picker",
  completePath: "pulse-md:complete-path",
  hydrateTab: "pulse-md:hydrate-tab",
  launchVisualEffectReady: "pulse-md:launch-visual-effect-ready",
  launchWindowProfile: "pulse-md:launch-window-profile",
  importSettings: "pulse-md:import-settings",
  windowProfilePickerRequested: "pulse-md:window-profile-picker-requested",
  windowProfilePickerCancelled: "pulse-md:window-profile-picker-cancelled",
  newTab: "pulse-md:new-tab",
  newScratch: "pulse-md:new-scratch",
  openExternalLink: "pulse-md:open-external-link",
  openExistingLocalLinkRequested: "pulse-md:open-existing-local-link-requested",
  openLocalLink: "pulse-md:open-local-link",
  openScratchLink: "pulse-md:open-scratch-link",
  openScratch: "pulse-md:open-scratch",
  locateDocument: "pulse-md:locate-document",
  openDocument: "pulse-md:open-document",
  openDroppedDocuments: "pulse-md:open-dropped-documents",
  previewAppearance: "pulse-md:preview-appearance",
  provideSettingsScratchSnapshot: "pulse-md:provide-settings-scratch-snapshot",
  provideTabExport: "pulse-md:provide-tab-export",
  recoveryAction: "pulse-md:recovery-action",
  recoveryWindowAction: "pulse-md:recovery-window-action",
  reportEditorMenuState: "pulse-md:report-editor-menu-state",
  reportLineWrapping: "pulse-md:report-line-wrapping",
  resolveHeadingLinkPaste: "pulse-md:resolve-heading-link-paste",
  releaseSettingsSession: "pulse-md:release-settings-session",
  revealPath: "pulse-md:reveal-path",
  rendererReady: "pulse-md:renderer-ready",
  reorderTab: "pulse-md:reorder-tab",
  requestCloseTab: "pulse-md:request-close-tab",
  requestTabTransfer: "pulse-md:request-tab-transfer",
  saveDocument: "pulse-md:save-document",
  saveWindowProfile: "pulse-md:save-window-profile",
  selectWindowProfileFiles: "pulse-md:select-window-profile-files",
  setActiveTab: "pulse-md:set-active-tab",
  setDirty: "pulse-md:set-dirty",
  setSettings: "pulse-md:set-settings",
  showRecovery: "pulse-md:show-recovery",
  setDefaultWindowProfile: "pulse-md:set-default-window-profile",
  startupCommand: "pulse-md:startup-command",
  settingsChanged: "pulse-md:settings-changed",
  settingsScratchSnapshotRequested:
    "pulse-md:settings-scratch-snapshot-requested",
  spellCheckDictionaryChanged: "pulse-md:spell-check-dictionary-changed",
  tabExportRequested: "pulse-md:tab-export-requested",
  tabDetachSourceRetired: "pulse-md:tab-detach-source-retired",
  tabDetachSourceSettled: "pulse-md:tab-detach-source-settled",
  tabDragActivity: "pulse-md:tab-drag-activity",
  tabTransferCommitRequested: "pulse-md:tab-transfer-commit-requested",
  tabTransferCommitSettled: "pulse-md:tab-transfer-commit-settled",
  tabsChanged: "pulse-md:tabs-changed",
  updateScratch: "pulse-md:update-scratch",
  windowAction: "pulse-md:window-action",
  windowActivationChanged: "pulse-md:window-activation-changed",
  windowMaximizedChanged: "pulse-md:window-maximized-changed",
  windowZoomChanged: "pulse-md:window-zoom-changed",
  windowZoomPersistenceFailed: "pulse-md:window-zoom-persistence-failed",
} as const
